/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/settings': typeof SettingsRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/settings': typeof SettingsRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents': typeof IncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/monitor': typeof MonitorRoute
  '/settings': typeof SettingsRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/monitor'
    | '/settings'
    | '/incidents/$id'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/monitor'
    | '/settings'
    | '/incidents/$id'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/monitor'
    | '/settings'
    | '/incidents/$id'
    | '/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  MonitorRoute: typeof MonitorRoute
  SettingsRoute: typeof SettingsRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  MonitorRoute: MonitorRoute,
  SettingsRoute: SettingsRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
